openshift-eng/jira-lifecycle-plugin

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
This PR makes string comparisons for `Status` and `Resolution` use
`strings.EqualFold` instead of `==`. Jira statuses are case-insensitive.
They are usually displayed in full caps via the UI, and that is what we
use for the config and when updating the status. However, the status and
resolution returned via `GetIssue` only capitalize the first letter.
=> server: make status checking case-insensitive

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
This PR fixes the handling of dependent bugs. The unit tests did not
catch this because they were written incorrectly. The tests have also
been fixed in this PR.
=> server: fix handling of dependents

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go, pkg/labels/label.go
This PR changes functionality of the `jira-lifecycle-plugin` to add the
`bugzilla/valid-bug` label alongside the usual `jira/valid-bug` label to
workaround `tide` not supporting "or" statements for required labels.
/c @bradmwilliams
=> labels: add `bugzilla/valid-bug` label to valid bugs

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
In cases where the `StateAfterValidation` is also part of the
`ValidStates` list, do not list the state twice.
=> server.go: don't duplicate valid states

cmd/jira-lifecycle-plugin/config.go, cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
This PR adds a validation check verifying that all dependent bugs are
part of the `OCPBUGS` project. If a dependent bug is not part of
`OCPBUGS`, the bot will also include instructions for backporting
Bugzilla bugs as part of its comment.
=> server: require `OCPBUGS` dependent bugs

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
This PR changes the behavior of the plugin to always add the external link to the Jira bug if a Jira bug is identified. The previous behavior only added the link after a bug passed validation.
=> server: always add external link

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
This fixes an issue with the bz backporting process. This also makes some of the tests look weird due to the fake client basing naming off of `Name` instead of `Key`, but that can be fixed later.
=> server: use `Key` instead of `Name` for project

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
This PR adds the issue type and affects version fields to new bugs
created via the backport process, as these are required fields for new
bugs in OCPBUGS.
=> server: set issue type and affects version for new bugs

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
This adds support for processing links that referencing commits on a GitHub PR.
=> server: allow PR commit external link

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go, pkg/labels/label.go
Extracts any jira reference of the form `XYZ-NNNN` from the PR title, and if it finds such a reference, and can find the associated jira ticket, it applies the "jira/valid-reference" label to the PR.
A reference of `NO-JIRA` or `NO-ISSUE` will also result in this label being applied.
This is intended as a building block towards eventually gating some repos on having a valid jira reference for all PRs.
Intent is not to change any behavior in terms of what happens when a bug is referenced, this behavior should only be additive.
=> FDN-112: Add jira/valid-reference label to PRs that reference any valid jira issue

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
If a user make a comment that has multiple lines, the plugin responds with an error:
https://github.com/openshift/cluster-image-registry-operator/pull/836#issuecomment-1413941431
GitHub's API returns the following:
```
"body": "/jira cherrypick OCPBUGS-6517\r\nTesting latest changes.  If successful, this new bug can be safely ignored and I will close it accordingly."
```
This is not necessarily the prettiest fix, but I couldnt get the regex to pick up the `\r`.
=> Enabling the processing of multi-line comments

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
In response to:
> can we change the logic to tolerate jiras that target openshift-4.15* (and 4.15*) instead of requiring openshift-4.15.0 (and 4.15.0)?
This PR changes the logic to check for `TargetVersions` that are not prefixed with a matching `Major.Minor` or `openshift-Major.Minor` version.
=> Change `TargetVersion` verification to check for X.Y.*

cmd/jira-lifecycle-plugin/config.go, cmd/jira-lifecycle-plugin/config_test.go, cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go, pkg/helpers/helpers.go
This PR adds 2 config options to configure release notes requirements for jira bugs.
=> server,config: add release notes requirement options

pkg/helpers/helpers.go
OCPBUGS reverted to the old customfield for Target Version. This PR swaps the names and should fix the plugin's cherrypick functionality.
=> helpers: swap target version custom field IDs

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go, pkg/helpers/helpers.go
This PR adds the `Assignee` as one of the values that gets updated after bug creation during the cherrypick cloning process. It also adds basic support for cloning the `Sprint` value during the post-clone update, but does not add the struct as the plugin does not need to parse any data from it. While `OCPBUGS` does not use the `Sprint` field, other projects do and while the plugin does not fully support non-OCPBUGS projects, this did not require too much extra effort to implement.
=> OCPCRT-259: server,helpers: add support for update assignee and Sprint during clone

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
This PR has a workaround for broken USHIFT cloning. It also temporarily disables setting of the Sprint field, as that breaks the update function.
=> server: fix USHIFT cloning

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
server: do less string manipulation, more regex
We already have regular expressions with capturing groups. Let's use
them! We can omit the couple of places we do similar
string-manipulation parsing and get more granular information about the
referenced Jira issues.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
server: say something when a user asks to cherry-pick the wrong thing
Current behavior is to not respond at all, which is pretty hard to grok
as a user.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
server: provide the correct help text
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
=> improve the user experience of this plugin

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go, pkg/helpers/helpers.go, pkg/helpers/helpers_test.go
This PR adds support for cloning the sprint field during cherrypicks of issues with an active sprint.
=> helpers,server: clone sprint field

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
This PR fixes a race condition where the inbuilt jira automation sets the Assignee of the clone to the project default after the plugin updates the Assignee to match the parent. This PR also moves the sprint field update into the same operation as the Target Version and Assignee update.
=> server: wait for jira assignee automation

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go, pkg/helpers/helpers.go
This adds a check to allow `Release Note Not Needed` set as the Release Note Type to override the release notes text requirement. This also changes the release note variables and functions to better match the jira fields.
=> server: add Release Note Type check

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
This PR adds an initial devcontainer json and Containerfile that uses the openshift-4.17 golang-1.22 builder image, makes adjustments to allow it to run in rootless podman, and installs commonly used golang tools. It also configures the vscode to enable the go and docker extensions in the devcontainer. Note that users will need to be logged into the quay-proxy registry to pull the base image for the Containerfile.
=> .devcontainer: add devcontainer

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
This PR adds some extra info specifying what issues were created and for what branches during a backport. This makes it easier for users to track what is going on without having to follow many links in the Jira UI.
=> server: improve comment for backport

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
Fixes a bug with handling jira's auto-assign functionality that conflicts with the plugin's assignee cloning.
=> server: fix assignee race condition

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
Fix a bug that was causing the plugin to fail to correctly create the childBranches map when a branch has both `.0` and `.z` dependents, but only a branch for the `.z` target version exists. Also handle situation where one target version could be required by multiple branches (for example, `main` and `release-4.X`).
=> server: fix backport bug caused by z-stream versions

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
This PR adds support for treating the `DFBUGS` project as a valid project for bugs, similar to `OCPBUGS`.
=> server.go: add support for DFBUGS project

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
Fix an issue in handling a failure for validation for dependent bugs matching their parent, where the errors slice would be the failed validation appended to passing validations. This PR also renames some variables for clarity.
=> OCPCRT-278: server.go: fix issue with non-matching parent validation

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go, pkg/helpers/helpers.go
This is a special case, for RedHat, to handle the cases if/when a Jira issue has been marked "Restricted" to allow for contributors from "other" locations the ability to cherrypick PR's associated to the corresponding Ticket.
This PR add a check to verify that `Red Hat Employee` is both:
1. an allowed security level
2. a member of the Contributors group
If both of these conditions are true, we'll allow further processing of the issue.
If not, no further processing will occur.
=> Processing `Restricted` Jira Issues

cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
don't split and compare target version value for DFBUGS project, because we need to validate the z-stream versions for each issues and then plan if the issue can be considered for the respective z-stream release.
Ref: https://github.com/red-hat-storage/odf-operator/pull/421#issuecomment-2597585141
=> server: don't split target version for DFBUGS project

cmd/jira-lifecycle-plugin/bigquery.go, cmd/jira-lifecycle-plugin/server.go, cmd/jira-lifecycle-plugin/server_test.go
Add the ability to remove the verified labels via a `/verified later` command and automatically remove the verified labels if a PR's contents are modified.
=> server: add verification removal functionality
